package com.antrocare.catalog.product;

final class ProductUseDescriptions {

    private ProductUseDescriptions() {
    }

    static String forProduct(String name) {
        return switch (name) {
            case "Philadelphia Collar" -> "Supports neck positioning after injury, strain, surgery, or posture stress.";
            case "Cervical Hard Collar (Adjustable)" -> "Limits neck motion while supporting recovery, alignment, and controlled positioning.";
            case "Cervical Soft Collar" -> "Provides gentle neck support for minor strain and posture comfort.";
            case "Cervical Traction Collar" -> "Helps maintain cervical traction positioning for supervised neck relief sessions.";
            case "Cervical Pillow" -> "Supports natural neck alignment during sleep, rest, recovery, and relaxation.";
            case "SOMI Brace" -> "Stabilizes head and upper neck posture during prescribed immobilization care.";
            case "Cervical Ortho Wedge (2.5, 3 inches etc.)" -> "Elevates the neck comfortably during rest, therapy, and posture support.";
            case "Neoprene Elbow Sleeve" -> "Provides warmth and compression for elbow strain, soreness, and support.";
            case "Elastic Elbow Sleeve" -> "Offers light elbow compression for daily comfort and movement support.";
            case "Neoprene Tennis Elbow Strap" -> "Targets forearm tendon pressure for tennis elbow discomfort during activity.";
            case "Fore Arm Cock Up Splint" -> "Positions wrist and forearm to support healing and functional rest.";
            case "Short Cock Up Splint" -> "Stabilizes the wrist in extension for comfort and controlled activity.";
            case "Universal Neoprene Wrist Wrap" -> "Wraps the wrist with adjustable compression for support and comfort.";
            case "Dynamic Cock Up Splint" -> "Assists wrist extension while allowing guided movement during rehabilitation therapy.";
            case "Dynamic Cock Up Finger Extension Splint" -> "Supports wrist positioning and finger extension during functional hand therapy.";
            case "Static Cock Up Splint" -> "Immobilizes the wrist for rest, recovery, reduced strain, and support.";
            case "Thumb Spica Splint" -> "Stabilizes thumb joints while supporting wrist comfort during daily tasks.";
            case "Hand ROM Brace" -> "Guides hand range of motion exercises during supervised rehabilitation programs.";
            case "Carpal Tunnel Splint" -> "Keeps wrist neutral to ease carpal tunnel pressure during rest.";
            case "Arm Sling" -> "Supports the arm after shoulder, elbow, or wrist injury recovery.";
            case "Shoulder Immobilizer with Sling" -> "Restricts shoulder movement while holding the arm securely during recovery.";
            case "Arm Immobilizer" -> "Keeps the arm positioned safely after injury or surgical care.";
            case "Shoulder Immobilizer" -> "Limits shoulder motion to protect healing tissues after injury care.";
            case "Shoulder Abduction Pillow" -> "Maintains shoulder abduction position after surgery or injury recovery care.";
            case "Shoulder Dislocation Support" -> "Supports shoulder stability after dislocation during protected daily movement recovery.";
            case "Shoulder Abduction Splint / Airplane Splint" -> "Holds shoulder abducted for protected healing and post operative positioning.";
            case "Humeral Fracture Brace" -> "Stabilizes upper arm fractures while allowing shoulder and elbow movement.";
            case "Clavicle Brace" -> "Draws shoulders back to support clavicle alignment and posture recovery.";
            case "PP Humeral Fracture Brace" -> "Supports humeral fracture stabilization with lightweight molded protection and comfort.";
            case "Femur Brace" -> "Stabilizes thigh and femur alignment after injury or surgical treatment.";
            case "Hip Orthosis" -> "Controls hip movement to support alignment, stability, and rehabilitation progress.";
            case "Hip Abduction Pillow" -> "Keeps hips separated after surgery to protect positioning and healing.";
            case "Hip Lower Extremity Orthosis (Child/Adult)" -> "Supports hip and leg alignment for children or adults rehabilitating.";
            case "Taylor's Brace" -> "Supports thoracic spine posture and limits forward bending during recovery.";
            case "Contoured Spinal Brace" -> "Contours around the torso to support spinal alignment and stability.";
            case "Scoliosis Support" -> "Assists scoliosis posture management with guided torso support and alignment.";
            case "Sternal Splint" -> "Supports sternum protection during cough, movement, and post surgical recovery.";
            case "Hyper Extension Support" -> "Promotes spinal extension while limiting flexion after prescribed back treatment.";
            case "Lumbar Sacral Contoured Belt (Double Support)" -> "Supports lower back and sacral region with firm double compression.";
            case "Neoprene High Lumbar Sacro Belt (Double Support)" -> "Provides high lumbar warmth, compression, and support for back discomfort.";
            case "Sacroiliac Belt" -> "Compresses sacroiliac joints to improve pelvic stability and daily comfort.";
            case "Lumbar Posture Brace (Porous Elastic)" -> "Encourages upright posture while supporting the lumbar region comfortably daily.";
            case "Orthopaedic Back Rest (High/Short)" -> "Supports seated spinal posture during work, travel, or recovery rest.";
            case "Adjustable Back Rest For Use On Bed" -> "Raises back angle in bed for comfortable supported resting positions.";
            case "Maternity Belt" -> "Supports growing abdomen and lower back during pregnancy movement comfort.";
            case "Neoprene Abdominal Support" -> "Provides abdominal warmth and compression for core support and comfort.";
            case "Abdominal Binder" -> "Compresses abdomen after surgery, delivery, or strain for support comfort.";
            case "Pelvic Binder" -> "Stabilizes pelvic region during injury recovery and supported movement comfort.";
            case "Colostomy Abdominal Belt" -> "Supports abdominal wall around colostomy appliances for secure comfort wear.";
            case "Neoprene Knee Support" -> "Provides knee warmth, compression, and support during daily movement activities.";
            case "Knee Immobiliser Short" -> "Restricts knee bending with shorter support after injury or surgery.";
            case "Knee Immobiliser Long" -> "Immobilizes knee over longer length for stronger post injury support.";
            case "Neoprene Hinged Knee Brace (ACL/PCL)" -> "Supports knee ligaments with hinges during controlled movement and rehabilitation.";
            case "Post Operative Knee Brace (ROM)" -> "Controls knee range of motion after surgery during rehabilitation therapy.";
            case "Neoprene Open Patella Knee Brace" -> "Supports knee while relieving patella pressure during movement and exercise.";
            case "Neoprene Valgus Knee Support" -> "Helps manage inward knee alignment during walking and activity support.";
            case "AK Artificial Limb TES Belt" -> "Secures above knee prosthesis suspension for confident daily mobility support.";
            case "AK Bilateral Artificial Limb TES Belt" -> "Secures bilateral above knee prostheses for balanced suspension and mobility.";
            case "Neoprene OA Hinged Knee Support" -> "Supports osteoarthritis knees with hinges, warmth, compression, and stability care.";
            case "Elastic Knee Cap" -> "Offers lightweight knee compression for everyday support and comfort use.";
            case "Neoprene Spiral Knee Brace" -> "Provides spiral stays for flexible knee stability during movement activities.";
            case "Neoprene Varus Knee Support" -> "Helps manage outward knee alignment during walking and activity support.";
            case "BK Artificial Limb TES Belt" -> "Secures below knee prosthesis suspension for safer daily mobility support.";
            case "KAFO Knee Support" -> "Supports knee ankle foot alignment during braced standing and walking.";
            case "Neoprene Fig 8 Anklet" -> "Supports ankle ligaments with figure eight compression during movement activities.";
            case "Ankle Stabilizer" -> "Stabilizes ankle joint to reduce twisting during walking or sports.";
            case "Ankle Fracture Splint" -> "Protects fractured ankle alignment during immobilization and early recovery care.";
            case "Walking Casting Shoe" -> "Protects casts while allowing safer walking during foot recovery care.";
            case "Ankle Night Splint (D Rotation Boot)" -> "Maintains ankle position overnight for stretching and contracture prevention support.";
            case "Hallux Valgus Splint" -> "Aligns big toe position to support hallux valgus comfort care.";
            case "Foot Drop Splint" -> "Supports foot lift positioning to improve safer stepping clearance walking.";
            case "Customised Foot Thumb Toe Immobiliser" -> "Immobilizes customized foot, thumb, or toe areas during healing recovery.";
            case "Dorsal Night Splint" -> "Holds foot dorsiflexion overnight for stretching and morning comfort support.";
            case "Ankle Walker Boot" -> "Protects ankle and foot injuries while allowing controlled walking recovery.";
            case "Tibial Brace" -> "Supports tibial alignment and lower leg stability during recovery movement.";
            case "Toe Separator / Ring Type" -> "Separates toes to reduce rubbing and improve alignment comfort daily.";
            case "Heel Cup" -> "Cushions heel impact to improve comfort during standing and walking.";
            case "Insole with Arch" -> "Supports foot arches to reduce strain during standing and walking.";
            case "Heel Strap" -> "Secures heel positioning to reduce slippage and improve walking comfort.";
            case "Artificial Silicon Breast" -> "Restores breast contour balance after surgery for natural clothing fit.";
            case "Silicon Exercise Ball" -> "Builds hand strength and grip control during therapy exercises sessions.";
            case "Weight Cuff (1/2kg, 1kg, 2kg up to 6kg)" -> "Adds adjustable resistance for limb strengthening during rehabilitation exercises sessions.";
            case "Thera Band" -> "Provides elastic resistance for strengthening, stretching, and mobility training routines.";
            case "Coccyx Cushion Square / Round" -> "Relieves tailbone pressure while sitting at home, work, or travel.";
            case "Varicose Vein Stocking up to Knee" -> "Provides graduated leg compression for varicose vein comfort below knee.";
            case "Varicose Vein Stocking up to Thigh" -> "Extends graduated compression above knee for thigh level venous support.";
            case "Compression Arm Sleeve" -> "Applies arm compression to support swelling management and circulation comfort.";
            case "Anti Embolism Knee Length" -> "Helps support venous flow below knee during limited mobility periods.";
            case "Anti Embolism Stocking up to Thigh" -> "Supports thigh length venous circulation during recovery or immobility periods.";
            case "Pneumatic Compression Medical Device (For Leg & Hand)" -> "Provides intermittent compression therapy for limb circulation and swelling support.";
            case "Grip Bandage" -> "Provides secure grip compression for dressings, support, and protection comfort.";
            case "Lymphedema Straps" -> "Applies adjustable compression to support lymphedema swelling management and comfort.";
            case "Lymphedema Straps (Thigh Level)" -> "Supports thigh lymphedema compression with adjustable pressure and secure fit.";
            case "Lymphedema Arm Straps" -> "Wraps the arm with adjustable compression for lymphedema support comfort.";
            case "Child Cervical Collar" -> "Supports a child's neck posture after strain or injury care.";
            case "Child Arm Sling Pouch" -> "Holds a child's arm securely after injury or surgical recovery.";
            case "Weight Jacket" -> "Provides calming weighted pressure for posture, sensory, and therapy support.";
            case "Child Weight Cuffs" -> "Adds gentle resistance for pediatric strengthening and therapy exercises sessions.";
            case "Child Customised Spinal Brace" -> "Supports pediatric spinal alignment with customized bracing and posture control.";
            case "Torticollis Brace" -> "Helps support neck positioning for torticollis therapy and alignment care.";
            case "Head Holder" -> "Stabilizes head posture for children needing supported positioning and control.";
            case "Post Liposuction Garment" -> "Provides compression after liposuction to support contouring and swelling control.";
            case "Burn Garments" -> "Applies pressure over burn scars to support healing and remodeling.";
            case "Head / Chin / Cervical Strap" -> "Compresses head, chin, and neck areas after procedures or swelling.";
            case "Full Hand Stocking (Upper Limb)" -> "Provides upper limb compression from hand for swelling management comfort.";
            case "Liposuction Garment (Male/Female)" -> "Supports postoperative body compression after liposuction for men and women.";
            case "Leg Stocking (Lower Limb)" -> "Applies lower limb compression to support circulation and swelling control.";
            case "Below Knee Stocking" -> "Provides below knee compression for comfort, circulation, and swelling support.";
            case "Gutter Walker" -> "Supports forearms during walking for users needing extra stability assistance.";
            case "Axillary Crutches" -> "Provides underarm walking support after leg injury or surgery recovery.";
            case "Non-Foldable Walker" -> "Offers steady walking support for balance, strength, and mobility confidence.";
            case "Foldable Walker (Aluminium)" -> "Provides lightweight walking support that folds for easy transport storage.";
            case "Foldable Walker Steel Powder Coated" -> "Provides durable foldable walking support with steel frame stability confidence.";
            case "Elbow Crutch Steel Powder Coated" -> "Supports walking with durable elbow crutch strength and stability control.";
            case "Elbow Crutch (Aluminium)" -> "Provides lightweight elbow crutch support for assisted walking mobility daily.";
            case "Tripod Adjustable Walking Stick (Aluminium)" -> "Adds three point stability for adjustable assisted walking support confidence.";
            case "Adjustable Walking Stick (Aluminium)" -> "Offers lightweight height adjustable support for safer daily walking balance.";
            case "Adjustable Steel Powder Coated Walking Stick" -> "Provides strong adjustable walking support with durable steel construction stability.";
            case "Quadripad Adjustable Walking Stick (Aluminium)" -> "Provides four point base stability for confident assisted walking support.";
            default -> "Supports clinical care selection with practical comfort and mobility guidance.";
        };
    }
}
